const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const sandbox={window:{}};
for(const file of ['construction-board.js','scene-audit.js','answer-geometry.js'])vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../dist/'+file),'utf8'),sandbox);
const {DongConstruct:construct,DongSceneAudit:audit,DongAnswerGeometry:geometry}=sandbox.window;
const copy=x=>JSON.parse(JSON.stringify(x));let checks=0;const test=fn=>{fn();checks++;};
// These are elementary property fixtures, not generated example questions,
// reference answers loaded by the solver, or claimed model accuracy tests.
const base={type:'circle',h:2,k:1,r:3,showDynamic:false,points:{A:[5,1],B:[2,4],C:[-1,1],D:[2,-2],P:[8,6]},objects:[],lines:[]};
const parts=[{index:1,answer:'设N为线段AB的中点。点P到直线AC的垂足为H，连接PH。分别作圆在A、B两点处的切线，两条切线交于点T。直线AC与BD交于点Q。',steps:[]}];
const scene=copy(base),report=geometry.install(scene,parts,construct),resolve=label=>audit.frame(scene,construct).engine.resolve(scene.objects.find(n=>n.label===label).id);
test(()=>assert.equal(report.unresolved.length,0,JSON.stringify(report)));
test(()=>assert.deepEqual([resolve('N').x,resolve('N').y],[3.5,2.5]));
test(()=>assert.deepEqual([resolve('H').x,resolve('H').y],[8,1]));
test(()=>assert.deepEqual([resolve('Q').x,resolve('Q').y],[2,1]));
test(()=>assert.deepEqual([resolve('T').x,resolve('T').y],[5,4]));
test(()=>assert.equal(scene.objects.filter(n=>n.op==='tangent').length,2));
test(()=>assert.equal(scene.objects.find(n=>n.label==='PH').op,'segment'));
const size=scene.objects.length;geometry.install(scene,parts,construct);
test(()=>assert.equal(scene.objects.length,size,'Repeated answer enrichment is idempotent'));
const originalScene=copy(scene);scene.points.A=[2,-2];
test(()=>assert.deepEqual([resolve('N').x,resolve('N').y],[2,1],'Midpoint follows edited endpoints rather than freezing answer coordinates'));
test(()=>assert.equal(resolve('A 点切线').o.y,-2,'Tangent stays linked to the point'));
const translated={type:'ellipse',h:7,k:-4,a:5,b:3,showDynamic:false,points:{},objects:[]};
const frame=audit.frame(translated,construct);
test(()=>assert.deepEqual([frame.engine.resolve('feature:O').x,frame.engine.resolve('feature:O').y],[7,-4]));
test(()=>assert.equal(frame.engine.resolve('feature:F'),null,'An ellipse has F₁/F₂, not an invented F alias'));
const dynamic={type:'parabola',p:1,direction:-1,h:2,k:3,theta:90,showDynamic:true,lineThrough:'focus2',pairedChord:{labels:['C','D']},theta2:120,points:{},objects:[]};
test(()=>assert.deepEqual([audit.frame(dynamic,construct).origin.x,audit.frame(dynamic,construct).origin.y],[1,3],'Parabola focus fallback matches board origin'));
test(()=>assert(audit.frame(dynamic,construct).features.some(p=>p.name==='C')&&audit.frame(dynamic,construct).features.some(p=>p.name==='D')));
const shared=copy(base);geometry.install(shared,[{index:1,answer:'N为AB中点。',steps:[]},{index:2,answer:'N为AB中点，连接PN。',steps:[]}],construct);audit.prepare(shared,'已知点A、B、P。',[],construct);
test(()=>assert.deepEqual(Array.from(shared.objects.find(n=>n.label==='N').parts),[1,2]));
test(()=>assert.equal(audit.visible(shared.objects.find(n=>n.label==='N'),2),true));
const untouched=copy(base);untouched.objects.push({id:'manualN',kind:'point',x:42,y:9,label:'N',source:'user'});const preserved=geometry.install(untouched,parts,construct);
test(()=>assert.equal(untouched.objects.find(n=>n.id==='manualN').x,42,'Manual objects are never replaced'));
test(()=>assert(preserved.conflicts.some(n=>n.label==='N'),'Preserved conflicting points are explicitly reported, not silently called consistent'));
const uncertain=copy(base),unresolved=geometry.install(uncertain,[{index:1,answer:'设N为XY中点。作点P处的切线。直线AC与AC交于点R。',steps:[]}],construct);
test(()=>assert(!uncertain.objects.some(n=>['N','R','P 点切线'].includes(n.label)),'No invented endpoints, coincident-line intersection or off-curve tangent'));
test(()=>assert(unresolved.unresolved.some(n=>n.label==='N')&&unresolved.unresolved.some(n=>n.label==='P 点切线')));
const negative=copy(base);geometry.install(negative,[{index:1,answer:'点P不在圆上，不能作点P处的切线。如果N为AB中点，讨论其它情形。',steps:[]}],construct);
test(()=>assert.equal(negative.objects.length,0,'Negative and hypothetical statements are not construction commands'));
const partial=copy(base);partial.polygons=[{id:'triangle',label:'△PAN',labels:['P','A','N']}];
const missing=audit.inspect(partial,'点P(8,6)',[{answer:'N为AB中点。在A、B两点处的切线交于点T。',steps:[]}],construct);
test(()=>assert(missing.answerMissing.includes('N')&&missing.answerMissing.includes('T')));
test(()=>assert.equal(missing.answerMissingLines.length,2));
test(()=>assert(missing.missingPolygons.includes('△PAN')));
const restored=copy(originalScene),complete=audit.inspect(restored,'',parts,construct);
test(()=>assert.equal(complete.answerMissing.length,0,JSON.stringify(complete)));
test(()=>assert.equal(complete.answerMissingLines.length,0));
test(()=>assert(complete.checks.some(n=>n.kind==='foot'&&n.passed)));
const noIntersections={type:'circle',r:1,points:{P:[3,0]},lineThrough:'point:P',theta:90,showDynamic:true,objects:[]};
test(()=>assert.deepEqual(Array.from(audit.inspect(noIntersections,'交于A、B两点',[],construct).unavailable),['A','B'],'Declared dynamic labels do not imply two real intersections'));
console.log('PASS answer geometry: '+checks+' dependency, exact-frame, idempotency, shared-part, rejected-fabrication and coverage checks');
