module.exports = async ({page, assert}) => {
  await page.locator('#question').fill('已知椭圆x²/4+y²/3=1，点P(1,3/2)在椭圆上，求椭圆在点P处的切线方程。');
  await page.locator('#solveButton').click();
  await page.waitForFunction(() => document.querySelector('#solution')?.textContent.includes('x+2y-4=0'));
  let scene=JSON.parse(await page.locator('#sceneJson').inputValue());
  let tangent=scene.lines.find(line=>line.role==='tangent');
  assert(tangent,'答案所得切线必须进入画板场景');
  assert.equal(tangent.equation,'x+2y-4=0');
  assert.equal(tangent.source,'derived');
  assert.equal(tangent.part,0);
  assert.equal(tangent.m,-0.5);
  assert.equal(tangent.b,2);
  assert.match(await page.locator('#layers').innerText(),/P 点切线 · 推导/);
  assert.match(await page.locator('#solution').innerText(),/局部代数核验通过/);

  await page.locator('#question').fill('圆x²+y²=25，点A(3,4)、B(-4,3)在圆上，证明A、B两点处的切线互相垂直。');
  await page.locator('#solveButton').click();
  await page.waitForFunction(() => document.querySelector('#solution')?.textContent.includes('方向向量点积为 0'));
  scene=JSON.parse(await page.locator('#sceneJson').inputValue());
  let pairTangents=scene.lines.filter(line=>line.role==='tangent');
  assert.deepEqual(pairTangents.map(line=>[line.point,line.equation]),[['A','3x+4y-25=0'],['B','4x-3y+25=0']]);
  assert.notEqual(pairTangents[0].pointRef,pairTangents[1].pointRef,'两条切线必须绑定两个不同切点');
  assert.match(await page.locator('#layers').innerText(),/A 点切线 · 推导/);
  assert.match(await page.locator('#layers').innerText(),/B 点切线 · 推导/);
  await page.locator('.verification-details summary').click();
  assert.match(await page.locator('#solution').innerText(),/通过 · 两切线垂直关系/);
  const onlineTangentPair=pairTangents.map(line=>({point:line.point,equation:line.equation,pointRef:line.pointRef,refs:line.refs,exact:line.exact,construction:line.construction,part:line.part}));

  await page.locator('#question').fill('圆x²+y²=25，A(3,4)、B(-4,3)在圆上，证明A点和B点处的切线互相垂直。');
  await page.locator('#solveButton').click();
  await page.waitForFunction(() => document.querySelector('#solution')?.textContent.includes('方向向量点积为 0'));
  scene=JSON.parse(await page.locator('#sceneJson').inputValue());
  assert.deepEqual(new Set(scene.lines.filter(line=>line.role==='tangent').map(line=>line.point)),new Set(['A','B']),'带“点”字后缀的复数表述也必须建立两条切线');

  await page.locator('#question').fill('已知椭圆x²/4+y²/3=1，点P(1,3/2)在椭圆上，求在点P处的法线方程。');
  await page.locator('#solveButton').click();
  await page.waitForFunction(() => document.querySelector('#solution')?.textContent.includes('4x-2y-1=0'));
  scene=JSON.parse(await page.locator('#sceneJson').inputValue());
  let normal=scene.lines.find(line=>line.role==='normal');
  assert(normal,'答案所得法线必须进入画板场景');
  assert.equal(normal.equation,'4x-2y-1=0');
  assert.equal(normal.source,'derived');
  assert.equal(normal.construction.schema,'dongjiexi-construction/v1');
  assert.equal(normal.construction.type,'normal_at');
  assert.match(await page.locator('#layers').innerText(),/P 点法线 · 推导/);
  assert.match(await page.locator('#solution').innerText(),/局部代数核验通过/);
  const onlineNormal={equation:normal.equation,exact:normal.exact,construction:normal.construction};

  await page.locator('#question').fill('已知圆x²+y²=9，点P(3,4)，l:y=1，m:x=0，求点P到l的垂足H的坐标。');
  await page.locator('#solveButton').click();
  await page.waitForFunction(() => document.querySelector('#solution')?.textContent.includes('H(3,1)'));
  scene=JSON.parse(await page.locator('#sceneJson').inputValue());
  let foot=scene.objects.find(item=>item.role==='perpendicular_foot');
  assert(foot,'答案所得垂足必须进入画板构造图');
  assert.deepEqual(foot.exact,{x:'3',y:'1'});
  assert.equal(foot.source,'derived');
  assert.equal(foot.op,'foot');
  assert.equal(foot.construction.type,'perpendicular_foot');
  assert.equal(scene.lines.find(line=>line.id===foot.construction.inputs.line)?.label,'l','多条直线存在时必须按名称选择 l');
  assert.equal(scene.showDynamic,false,'有明确方程的直线不能再生成无关旋转动直线');
  assert.equal(scene.dynamicLine,false,'浏览器导出的 Python 兼容别名必须保持同一语义');
  assert.match(await page.locator('#layers').innerText(),/H · 推导/);
  assert.match(await page.locator('#solution').innerText(),/局部代数核验通过/);
  const onlineFoot={exact:foot.exact,construction:foot.construction};

  await page.locator('#question').fill('圆x²+y²=9与直线y=0交于A、B，求AB的长度和中点坐标。');
  await page.locator('#solveButton').click();
  await page.waitForFunction(() => document.querySelector('#solution')?.textContent.includes('弦长 |AB|=6'));
  scene=JSON.parse(await page.locator('#sceneJson').inputValue());
  let endpoints=scene.objects.filter(item=>item.role==='line_conic_intersection');
  let chord=scene.objects.find(item=>item.role==='derived_chord');
  let midpoint=scene.objects.find(item=>item.role==='derived_midpoint');
  assert.deepEqual(endpoints.map(item=>item.exact),[{x:'-3',y:'0'},{x:'3',y:'0'}]);
  assert.deepEqual(endpoints.map(item=>item.label),['A','B']);
  assert.equal(endpoints[0].construction.type,'line_conic_intersection');
  assert.equal(endpoints[0].construction.schema,'dongjiexi-construction/v1');
  assert.deepEqual(chord.refs,endpoints.map(item=>item.id));
  assert.deepEqual(chord.exact,{length:'6'});
  assert.deepEqual(midpoint.exact,{x:'0',y:'0'});
  assert.equal(midpoint.part,0);
  assert.match(await page.locator('#layers').innerText(),/弦 AB · 推导/);
  assert.match(await page.locator('#layers').innerText(),/M · 推导/);
  assert.match(await page.locator('#solution').innerText(),/局部代数核验通过/);
  const onlineChord=scene.objects.filter(item=>['line_conic_intersection','derived_chord','derived_midpoint'].includes(item.role)).map(item=>({role:item.role,label:item.label,refs:item.refs,exact:item.exact,construction:item.construction,part:item.part}));

  await page.locator('#question').fill('圆x²+y²=9与直线y=0交于A、B。（1）求A、B坐标；（2）求圆在A点处的切线方程。');
  await page.locator('#solveButton').click();
  await page.locator('[data-study-part="2"]').click();
  await page.waitForFunction(() => document.querySelector('#solution')?.textContent.includes('x+3=0'));
  scene=JSON.parse(await page.locator('#sceneJson').inputValue());
  tangent=scene.lines.find(line=>line.role==='tangent');
  const tangentPoint=scene.objects.find(item=>item.id===tangent.pointRef);
  assert.equal(tangent.equation,'x+3=0');
  assert.equal(tangent.part,2);
  assert.equal(tangentPoint.label,'A');
  assert.deepEqual(tangentPoint.exact,{x:'-3',y:'0'});
  assert.deepEqual(tangent.refs,[tangentPoint.id,'$conic']);
  assert.match(await page.locator('#layers').innerText(),/A 点切线 · 推导/);
  assert.match(await page.locator('#solution').innerText(),/局部代数核验通过/);
  const onlineComputedTangent={equation:tangent.equation,pointRef:tangent.pointRef,refs:tangent.refs,exact:tangent.exact,construction:tangent.construction,part:tangent.part};

  await page.locator('#question').fill('已知椭圆x²/9+y²/4=1，点P为椭圆上的动点，点Q(1,0)，M为线段PQ的中点，求点M的轨迹方程并画出轨迹。');
  await page.locator('#solveButton').click();
  await page.waitForFunction(() => document.querySelector('#solution')?.textContent.includes('(x-1/2)²/(9/4)+y²=1'));
  scene=JSON.parse(await page.locator('#sceneJson').inputValue());
  let locus=scene.objects.find(item=>item.role==='derived_locus');
  assert(locus,'答案所得轨迹必须进入画板场景');
  assert.equal(locus.equation,'(x-1/2)²/(9/4)+y²=1');
  assert.equal(locus.conicType,'ellipse');
  assert.equal(locus.a,1.5);
  assert.equal(locus.b,1);
  assert.equal(locus.h,0.5);
  assert.deepEqual(locus.exact.a2,'9/4');
  assert.match(await page.locator('#layers').innerText(),/M 的轨迹 · 推导/);
  assert.match(await page.locator('#solution').innerText(),/局部代数核验通过/);
  const locusMotion=await page.evaluate(sceneData=>{const model=structuredClone(sceneData),features=()=>Object.entries(model.points||{}).map(([name,[x,y]])=>({name,x,y})),conicPoint=t=>({x:model.h+model.a*Math.cos(t),y:model.k+model.b*Math.sin(t)}),engine=window.DongConstruct.createEngine({model:()=>model,features,coeffs:()=>({A:1/9,B:0,C:1/4,D:0,E:0,F:-1}),origin:()=>({x:0,y:0}),angle:()=>0,conicPoint,conicProject:()=>({t:0})}),moving=model.objects.find(item=>item.label==='P'&&item.op==='point_on'),middle=model.objects.find(item=>item.label==='M'&&item.op==='midpoint');moving.t=0;const first=engine.resolve(middle.id);moving.t=Math.PI/2;const second=engine.resolve(middle.id),residual=point=>(point.x-.5)**2/(9/4)+point.y**2-1;return{first,second,residuals:[residual(first),residual(second)]};},scene);
  assert.notDeepEqual(locusMotion.first,locusMotion.second,'动点变化后中点必须沿轨迹同步移动');
  assert(locusMotion.residuals.every(value=>Math.abs(value)<1e-8),'中点的每个采样位置都必须满足推导轨迹方程');
  const onlineLocus={equation:locus.equation,kind:locus.kind,conicType:locus.conicType,h:locus.h,k:locus.k,a:locus.a,b:locus.b,refs:locus.refs,construction:locus.construction,part:locus.part};

  await page.route('**/api/solve',route=>route.abort('failed'));
  await page.locator('#question').fill('圆x²+y²=9，点P(0,3)在圆上，求在点P处的切线方程。');
  await page.locator('#solveButton').click();
  await page.waitForFunction(() => document.querySelector('#solution')?.textContent.includes('y-3=0'));
  scene=JSON.parse(await page.locator('#sceneJson').inputValue());
  tangent=scene.lines.find(line=>line.role==='tangent');
  assert.equal(tangent.equation,'y-3=0');
  assert.equal(tangent.source,'derived');
  assert.equal(tangent.part,0);
  assert.equal(tangent.m,0);
  assert.equal(tangent.b,3);

  await page.locator('#question').fill('圆x²+y²=25，点A(3,4)、B(-4,3)在圆上，证明A、B两点处的切线互相垂直。');
  await page.locator('#solveButton').click();
  await page.waitForFunction(() => document.querySelector('#solution')?.textContent.includes('方向向量点积为 0'));
  scene=JSON.parse(await page.locator('#sceneJson').inputValue());
  pairTangents=scene.lines.filter(line=>line.role==='tangent');
  const offlineTangentPair=pairTangents.map(line=>({point:line.point,equation:line.equation,pointRef:line.pointRef,refs:line.refs,exact:line.exact,construction:line.construction,part:line.part}));
  assert.deepEqual(offlineTangentPair,onlineTangentPair,'在线与离线的双切线构造契约必须一致');
  assert.match(await page.locator('#layers').innerText(),/A 点切线 · 推导/);
  assert.match(await page.locator('#layers').innerText(),/B 点切线 · 推导/);
  await page.locator('.verification-details summary').click();
  assert.match(await page.locator('#solution').innerText(),/通过 · 两切线垂直关系/);

  await page.locator('#question').fill('已知椭圆x²/4+y²/3=1，点P(1,3/2)在椭圆上，求在点P处的法线方程。');
  await page.locator('#solveButton').click();
  await page.waitForFunction(() => document.querySelector('#solution')?.textContent.includes('4x-2y-1=0'));
  scene=JSON.parse(await page.locator('#sceneJson').inputValue());
  normal=scene.lines.find(line=>line.role==='normal');
  assert.deepEqual({equation:normal.equation,exact:normal.exact,construction:normal.construction},onlineNormal,'在线与离线法线契约必须一致');

  await page.locator('#question').fill('已知椭圆x²/4+y²/3=1，点P(1,3/2)在椭圆上，求在点P处的法线。（1）写出法线方程；（2）求离心率。');
  await page.locator('#solveButton').click();
  await page.waitForFunction(() => document.querySelector('#solution')?.textContent.includes('4x-2y-1=0'));
  scene=JSON.parse(await page.locator('#sceneJson').inputValue());
  normal=scene.lines.find(line=>line.role==='normal');
  assert.equal(normal.part,1,'第一小问之前出现的派生要求必须绑定最近的下一小问，不能成为全局核验对象');

  await page.locator('#question').fill('已知圆x²+y²=9，点P(3,4)，l:y=1，m:x=0，求点P到l的垂足H的坐标。');
  await page.locator('#solveButton').click();
  await page.waitForFunction(() => document.querySelector('#solution')?.textContent.includes('H(3,1)'));
  scene=JSON.parse(await page.locator('#sceneJson').inputValue());
  foot=scene.objects.find(item=>item.role==='perpendicular_foot');
  assert.deepEqual({exact:foot.exact,construction:foot.construction},onlineFoot,'在线与离线垂足契约必须一致');

  await page.locator('#question').fill('圆x²+y²=9与直线y=0交于A、B，求AB的长度和中点坐标。');
  await page.locator('#solveButton').click();
  await page.waitForFunction(() => document.querySelector('#solution')?.textContent.includes('弦长 |AB|=6'));
  scene=JSON.parse(await page.locator('#sceneJson').inputValue());
  const offlineChord=scene.objects.filter(item=>['line_conic_intersection','derived_chord','derived_midpoint'].includes(item.role)).map(item=>({role:item.role,label:item.label,refs:item.refs,exact:item.exact,construction:item.construction,part:item.part}));
  assert.deepEqual(offlineChord,onlineChord,'在线与离线交点、弦和中点契约必须一致');

  await page.locator('#question').fill('圆x²+y²=9与直线y=0交于A、B。（1）求A、B坐标；（2）求圆在A点处的切线方程。');
  await page.locator('#solveButton').click();
  await page.locator('[data-study-part="2"]').click();
  await page.waitForFunction(() => document.querySelector('#solution')?.textContent.includes('x+3=0'));
  scene=JSON.parse(await page.locator('#sceneJson').inputValue());
  tangent=scene.lines.find(line=>line.role==='tangent');
  assert.deepEqual({equation:tangent.equation,pointRef:tangent.pointRef,refs:tangent.refs,exact:tangent.exact,construction:tangent.construction,part:tangent.part},onlineComputedTangent,'在线与离线的计算点切线契约必须一致');

  await page.locator('#question').fill('已知椭圆x²/9+y²/4=1，点P为椭圆上的动点，点Q(1,0)，M为线段PQ的中点，求点M的轨迹方程并画出轨迹。');
  await page.locator('#solveButton').click();
  await page.waitForFunction(() => document.querySelector('#solution')?.textContent.includes('(x-1/2)²/(9/4)+y²=1'));
  scene=JSON.parse(await page.locator('#sceneJson').inputValue());
  locus=scene.objects.find(item=>item.role==='derived_locus');
  assert.deepEqual({equation:locus.equation,kind:locus.kind,conicType:locus.conicType,h:locus.h,k:locus.k,a:locus.a,b:locus.b,refs:locus.refs,construction:locus.construction,part:locus.part},onlineLocus,'在线与离线轨迹曲线契约必须一致');
  assert.match(await page.locator('#layers').innerText(),/M 的轨迹 · 推导/);

  await page.locator('#question').fill('圆x²+y²=9，点P(0,0)，求在点P处的切线方程。');
  await page.locator('#solveButton').click();
  await page.waitForFunction(() => document.querySelector('#solution')?.textContent.includes('没有把其它方程冒充为切线'));
  scene=JSON.parse(await page.locator('#sceneJson').inputValue());
  assert.equal(scene.lines.some(line=>line.role==='tangent'),false);
  await page.unroute('**/api/solve');
  console.log('PASS: computed-point tangents and exact midpoint loci join tangents, normals, feet, intersections, chords and midpoints in one verified online/offline scene contract.');
};
