module.exports=async({page,assert,screenshot})=>{
  await page.locator('#openQuestionBank').click();await page.locator('#bankList button').first().waitFor();
  await page.locator('#bankPaper').selectOption('national-i');await page.locator('[data-bank-id="2025-i-18"]').click();await page.locator('[data-bank-action="full"]').click();
  await page.locator('[data-study-part="202"]').click();
  assert.equal(await page.locator('#unrestrictedMove').getAttribute('aria-pressed'),'false');
  assert.match(await page.locator('#motionConstraintStatus').innerText(),/按题设移动/);
  const saved=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('zhigeometry:last')));
  const scene=async()=>(await saved()).scene;
  const points=async()=>page.evaluate(model=>{
    const curve=window.DongConstruct.conicShape({...model,conicType:model.type});
    const e=window.DongConstruct.createEngine({model:()=>model,features:()=>Object.entries(model.points).map(([name,[x,y]])=>({name,x,y})),coeffs:()=>curve.q,conicPoint:curve.pointAt,conicProject:curve.project});
    return {P:e.resolve('inverse-moving-P'),M:e.resolve('inverse-moving-M'),R:e.resolve('inverse-derived-R'),A:e.resolve('feature:A')};
  },await scene());
  const fit=async()=>{await page.locator('#homeButton').click();const box=await page.locator('#canvas').boundingBox(),r=Math.sqrt(18);const scale=Math.max(2*Math.max(3*1.75,1.3*r)/box.width,2*(4+1.3*r)/box.height);return(x,y)=>({x:box.x+box.width/2+x/scale,y:box.y+box.height/2-y/scale});};
  let xy=await fit();
  const drag=async(from,to)=>{const a=xy(from.x,from.y),b=xy(to.x,to.y);await page.mouse.move(a.x,a.y);await page.mouse.down();await page.mouse.move(b.x,b.y,{steps:12});await page.mouse.up();};
  const original=(await saved()).solution.parts;
  const check=async()=>{const p=await points();assert(Math.abs(p.P.x*p.P.x+(p.P.y+4)**2-18)<1e-8);assert(Math.abs(p.M.x*p.M.x/9+p.M.y*p.M.y-1)<1e-8);assert(Math.abs(Math.hypot(p.R.x-p.A.x,p.R.y-p.A.y)*Math.hypot(p.P.x-p.A.x,p.P.y-p.A.y)-3)<1e-8);assert(Math.abs(p.R.y/p.R.x-3*p.P.y/p.P.x)<1e-7);return p;};
  let p=await points(),start=p.P;
  await drag(p.P,{x:6,y:-5});p=await check();assert(Math.hypot(p.P.x-start.x,p.P.y-start.y)>1,'实际拖动必须改变受约束参数');
  assert.equal((await saved()).exploring,false,'合法运动不提示题设已被改变');
  await page.locator('#undoDrag').click();assert(Math.abs((await points()).P.x-start.x)<1e-8);await page.locator('#redoDrag').click();
  await page.locator('#motionPlay').click();await page.waitForTimeout(350);await page.locator('#motionPlay').click();await check();assert.equal((await saved()).exploring,false,'合法联动播放也保持题设');
  p=await points();await drag(p.M,{x:-5,y:2});p=await check();assert(p.M.x<0);
  let legal=p.P;
  await drag(p.P,{x:0,y:4});await check();assert(Math.abs((await points()).P.x)>1e-7,'排除 y 轴交点');
  legal=(await points()).P;
  const fixed=(await scene()).points.A;
  await drag({x:0,y:-1},{x:4,y:2});assert.deepEqual((await scene()).points.A,fixed);assert.match(await page.locator('#dragHint').textContent(),/固定对象/);
  await page.locator('[data-inspector-view="geometry"]').click();await page.locator('#parameterTarget').selectOption('$conic');
  assert(await page.locator('#params input[data-key="a"][type="text"]').isDisabled());
  await page.locator('#unrestrictedMove').click();assert.equal(await page.locator('#unrestrictedMove').getAttribute('aria-pressed'),'true');
  xy=await fit();
  p=await points();await drag(p.P,{x:4,y:6});p=await points();assert(Math.abs(p.P.x-4)<1e-4&&Math.abs(p.P.y-6)<1e-4,'自由模式允许离开轨迹');
  await drag(p.R,{x:2,y:3});p=await points();assert(Math.abs(p.R.x-2)<1e-4&&Math.abs(p.R.y-3)<1e-4,'关联点可显式脱离构造');
  await page.locator('#params input[data-key="a"][type="text"]').fill('6');assert.equal((await scene()).a,6);
  await page.locator('#unrestrictedMove').click();assert.equal((await scene()).a,3);p=await check();assert(Math.abs(p.P.x-legal.x)<1e-8);
  assert.equal(await page.locator('#unrestrictedMove').getAttribute('aria-pressed'),'false');
  assert.deepEqual((await saved()).solution.parts,original,'移动不改写原题解析');
  await page.locator('#undoDrag').click();assert.equal(await page.locator('#unrestrictedMove').getAttribute('aria-pressed'),'true');await page.locator('#redoDrag').click();await check();
  await screenshot('constrained-trajectory-and-inverse.png');
  await page.reload({waitUntil:'domcontentloaded'});assert.equal(await page.locator('#unrestrictedMove').getAttribute('aria-pressed'),'false');await check();
  await page.setViewportSize({width:390,height:844});await page.locator('[data-mobile-panel="board"]').click();
  assert(await page.locator('#unrestrictedMove').isVisible(),'手机无需展开作图工具即可切换');await page.locator('#unrestrictedMove').click();assert.equal(await page.locator('#unrestrictedMove').getAttribute('aria-pressed'),'true');await page.locator('#unrestrictedMove').click();
  assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));
  await screenshot('motion-toggle-mobile.png');
};
