module.exports=async({page,assert,screenshot})=>{
  await page.locator('#question').fill('椭圆 C：x²/4+y²=1。');
  await page.locator('#solveButton').click();
  await page.waitForFunction(()=>!document.querySelector('#solveButton').disabled);
  const data=async()=>JSON.parse(await page.locator('#sceneJson').inputValue());
  assert.equal(await page.locator('#parameterTarget').inputValue(),'');
  assert.equal(await page.locator('#params input').count(),0,'未选择方程时不应直接展开主曲线参数');
  await page.locator('[data-inspector-view="geometry"]').click();
  await page.locator('#parameterTarget').selectOption('$conic');
  await page.locator('#params input[data-key="a"][data-param-expression]').fill('√8');
  await page.locator('#params input[data-key="h"][data-param-expression]').fill('1/3');
  const main=await data();assert(Math.abs(main.a-Math.sqrt(8))<1e-10);assert.equal(main.h,1/3);
  await page.locator('#objectBuilderDetails > summary').click();
  await page.locator('#objectType').selectOption('circle');
  await page.locator('#objectParam-r').fill('√3');
  await page.locator('#objectName').fill('测试圆');await page.locator('#addObject').click();
  let circle=(await data()).objects.at(-1);const id=circle.id;
  await page.locator('#parameterTarget').selectOption(id);
  assert.equal(await page.locator('#selectedParam-r').inputValue(),'√3');
  await page.locator('#selectedParam-r').fill('√5');await page.locator('#applySelectedParameters').click();
  let scene=await data();circle=scene.objects.find(o=>o.id===id);assert(Math.abs(circle.r-Math.sqrt(5))<1e-10);assert.equal(scene.a,main.a,'修改附加圆不能改变主椭圆');
  await page.locator('#objectType').selectOption('function');await page.locator('#equationTemplate').selectOption('sine');
  await page.locator('#objectParam-A').fill('1+√2');await page.locator('#objectParam-w').fill('π/2');await page.locator('#objectParam-d').fill('1/3');
  await page.locator('#objectName').fill('f');await page.locator('#addObject').click();
  const fn=(await data()).objects.at(-1);
  await page.locator('#parameterTarget').selectOption(fn.id);
  assert.equal(await page.locator('#selectedParam-A').inputValue(),'1+√2');
  assert.equal(await page.locator('#selectedParam-w').inputValue(),'π/2');
  await page.locator('#selectedParam-A').fill('1+√3');await page.locator('#applySelectedParameters').click();
  scene=await data();const modified=scene.objects.find(o=>o.id===fn.id);
  assert(Math.abs(modified.params.A-(1+Math.sqrt(3)))<1e-10);assert.match(modified.equation,/√3/);
  await page.locator('#parameterTarget').selectOption('$conic');
  assert.equal(await page.locator('#params input[data-key="a"][data-param-expression]').inputValue(),'√8');
  assert.equal(await page.locator('#params input[data-key="h"][data-param-expression]').inputValue(),'1/3');
  await page.locator('#parameterTarget').scrollIntoViewIfNeeded();
  await screenshot('selected-parameters.png',null);
  await page.reload({waitUntil:'domcontentloaded'});
  await page.locator('[data-inspector-view="geometry"]').click();
  await page.locator('#parameterTarget').selectOption(fn.id);
  assert.equal(await page.locator('#selectedParam-A').inputValue(),'1+√3','刷新后表达式不能变成小数');
  assert.equal(await page.locator('#selectedParam-d').inputValue(),'1/3');
};
