const fs=require('node:fs'),path=require('node:path');
module.exports=async({page,context,assert,screenshot})=>{
  await context.route('**/runtime-config.js',r=>r.fulfill({contentType:'application/javascript',body:'window.DONGJIEXI_CONFIG={deployment:"web",apiEnabled:false};'}));
  await page.reload({waitUntil:'domcontentloaded'});
  const bank=JSON.parse(fs.readFileSync(path.join(__dirname,'../dist/question-bank.json'),'utf8')),original=bank.items.find(q=>q.id==='2023-i-22').question;
  await page.locator('#question').fill(original);await page.locator('#solveButton').click();
  await page.waitForFunction(()=>document.querySelector('#solveProgress').dataset.state==='complete');
  const read=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('zhigeometry:last')));
  let saved=await read();
  assert.deepEqual(saved.solution.completion,{answered:2,total:2});
  assert(saved.scene.objects.some(n=>n.label==='P'&&n.op==='point_on'));
  assert(saved.scene.objects.some(n=>n.op==='foot'));
  assert.equal(saved.scene.showDynamic,false);
  assert.equal(saved.scene.polygons.filter(n=>(n.labels||[]).join('')==='ABCD').length,1,'One rectangle is not painted twice');
  assert.equal(await page.locator('#solution .katex-error').count(),0);
  await screenshot('parabola-definition.png',null);
  await page.locator('[data-study-part="2"]').click();
  await page.locator('[data-inspector-view="geometry"]').click();
  await page.locator('#parameterTarget').selectOption('$rectangle');
  async function set(key,value){await page.locator('[data-rectangle-param="'+key+'"]').evaluate((el,value)=>{el.value=value;el.dispatchEvent(new Event('input',{bubbles:true}));},value);}
  await set('b','1/4');await set('u','sqrt(2)');
  saved=await read();
  const coords=saved.scene.points,[A,B,C,D]=saved.scene.rectangularParabola.names.map(n=>coords[n]);
  for(const [x,y]of[A,B,C])assert(Math.abs(y-x*x-.25)<1e-9);
  assert(Math.abs((A[0]-B[0])*(C[0]-B[0])+(A[1]-B[1])*(C[1]-B[1]))<1e-9);
  assert(D.every((v,i)=>Math.abs(v-A[i]-C[i]+B[i])<1e-9));
  assert.match(await page.locator('#metrics').innerText(),/合法演示构型/);
  assert.match(await page.locator('#metrics').innerText(),/3√3/);
  await set('u','1');await set('b','1/2');
  assert.match(await page.locator('#metrics').innerText(),/退化/);
  await set('b','0');
  await screenshot('parabola-rectangle-controls.png',null);
  await page.setViewportSize({width:320,height:740});
  await page.locator('[data-mobile-panel="board"]').click();
  assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));
  assert.equal(await page.locator('.controls').isVisible(),false);
  await screenshot('parabola-rectangle-mobile.png',null);
  await page.setViewportSize({width:1600,height:1050});
  await page.reload({waitUntil:'domcontentloaded'});
  saved=await read();assert(saved.scene.rectangularParabola,'Restored draft retains rectangle controls');
  assert.equal(saved.scene.curveLabel,'W');
  await page.locator('#question').fill('在直角坐标系中，点P到x轴的距离等于点P到点(0,1/2)的距离，求P的轨迹方程。');
  await page.locator('#solveButton').click();
  await page.waitForFunction(()=>document.querySelector('#solveProgress').dataset.state==='complete');
  assert.equal((await read()).solution.completion.answered,1,'Premise distances are not additional solve goals');
};
