const fs=require('node:fs'),path=require('node:path');
module.exports=async({page,context,assert,screenshot})=>{
  // All mathematical content comes from a sourced 2022 Beijing exam question.
  // Only the returned UI status is mocked in the XSS and empty-match cases.
  const exam=JSON.parse(fs.readFileSync(path.join(__dirname,'fixtures/sourced-exam-additions.json'),'utf8')).items.find(item=>item.id==='2022-beijing-19-full');
  await context.route('**/runtime-config.js',route=>route.fulfill({contentType:'application/javascript',body:'window.DONGJIEXI_CONFIG={deployment:"web",apiEnabled:false};'}));
  await context.addInitScript(()=>{
    let learning;
    Object.defineProperty(window,'DongLearning',{configurable:true,get:()=>learning,set:value=>{
      learning=value;
      const attach=value.attach;
      value.attach=function(api){
        const actualHighlight=api.highlightStep,actualClear=api.clearStepHighlight;
        window.__stepLinkTest={api,calls:[],clears:0,result:null};
        api.highlightStep=input=>{
          const test=window.__stepLinkTest;test.calls.push(input);
          const result=actualHighlight?.(input);
          return test.result??result;
        };
        api.clearStepHighlight=()=>{window.__stepLinkTest.clears++;actualClear?.();};
        return attach(api);
      };
    }});
  });
  await page.reload({waitUntil:'domcontentloaded'});
  await page.locator('#question').fill(exam.question);await page.locator('#solveButton').click();
  await page.waitForFunction(()=>document.querySelector('#solveProgress').dataset.state==='complete');
  assert.equal(await page.locator('.step-graph-toolbar').isHidden(),true,'The linkage toolbar does not add expanded clutter before selection');
  // Part 1 begins with algebraic parameters; part 2 names the actual P/A points.
  await page.getByRole('button',{name:'第（2）问',exact:true}).click();
  const first=page.locator('#solution [data-step-graph-index]').first();
  await first.focus();await page.keyboard.press('Enter');
  assert.equal(await first.getAttribute('aria-pressed'),'true','Keyboard activation selects the real step');
  const call=await page.evaluate(()=>window.__stepLinkTest.calls.at(-1));
  const realStep=await page.evaluate(({part,index})=>window.__stepLinkTest.api.state.solution.parts.find(p=>Number(p.index)===part).steps[index],call);
  assert.equal(call.text,realStep,'Raw original step text, not rendered or inferred geometry, is passed to the board');
  assert.match(await page.locator('[data-step-graph-status]').textContent(),/已高亮/,'Actual sourced step matches actual visible scene objects');
  assert.match(await page.locator('[data-step-graph-status]').textContent(),/不代表本步证明通过/);
  await page.keyboard.press('Space');
  assert.equal(await first.getAttribute('aria-pressed'),'false','Space toggles the selection off');
  assert.equal(await page.locator('.step-graph-toolbar').isHidden(),true);
  assert.equal(await page.evaluate(()=>window.DongBoardStep.snapshot()),null,'Toggling off clears actual highlight IDs, not only the toolbar');
  await first.click();
  await page.getByRole('button',{name:'第（1）问',exact:true}).click();
  assert.equal(await page.locator('.step-graph-toolbar').isHidden(),true,'Changing part clears selection');
  assert.equal(await page.evaluate(()=>window.DongBoardStep.snapshot()),null);
  await page.getByRole('button',{name:'第（2）问',exact:true}).click();
  const step=page.locator('#solution [data-step-graph-index]').first();
  const before=await page.locator('#sceneJson').inputValue();
  await page.evaluate(()=>{window.__stepLinkTest.result={matched:['A','<img src=x onerror="window.__stepUnsafe=true">'],missing:['N\"] [data-any="x']};});
  await step.click();
  assert.match(await page.locator('[data-step-graph-status]').textContent(),/未找到或未显示：N/);
  assert.equal(await page.locator('.step-graph-toolbar img').count(),0,'Returned object names remain literal text');
  assert.equal(await page.evaluate(()=>!!window.__stepUnsafe),false);
  assert.equal(await page.locator('#sceneJson').inputValue(),before,'Highlighting never modifies geometry or its equations');
  await page.locator('[data-step-graph-clear]').click();
  await page.evaluate(()=>{window.__stepLinkTest.result={matched:[],missing:['未显示点']};});
  await step.click();
  assert.match(await page.locator('[data-step-graph-status]').textContent(),/本步未匹配到可见图形/,'An empty match is reported, never pretended to be solved');
  const saved=await page.evaluate(()=>{const api=window.__stepLinkTest.api;return{format:'dongjiexi-lesson',version:1,question:api.question.value,solution:api.state.solution,activePart:api.state.activePart,scene:api.sceneData()};});
  await page.locator('#question').fill(exam.question+' ');
  assert.equal(await page.locator('.step-graph-toolbar').isHidden(),true,'Editing the question immediately clears selection');
  assert.equal(await page.evaluate(()=>window.DongBoardStep.snapshot()),null);
  await page.locator('#question').fill(exam.question+'\n待补充');
  await step.click();
  assert.equal(await step.getAttribute('aria-pressed'),'false');
  assert.match(await page.locator('#status').textContent(),/重新解题/,'A stale answer cannot select geometry for a changed question');
  await page.locator('#importLesson').setInputFiles({name:'sourced-beijing-lesson.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(saved))});
  assert.equal(await page.locator('.step-graph-toolbar').isHidden(),true,'Restoring a saved lesson does not restore transient step selection');
  await page.evaluate(()=>{window.__stepLinkTest.result=null;});
  await page.locator('[data-inspector-view="lesson"]').click();
  await page.locator('#solution [data-step-graph-index]').first().click();
  await page.locator('[data-inspector-view="geometry"]').click();
  await page.locator('#resetParams').click();
  assert.equal(await page.locator('.step-graph-toolbar').isHidden(),true,'Restoring initial graph parameters clears selected highlights');
  await page.evaluate(()=>{window.__copiedLesson='';Object.defineProperty(navigator.clipboard,'writeText',{configurable:true,value:async text=>{window.__copiedLesson=text;}});window.print=()=>{window.__printedLesson=true;};});
  await page.locator('[data-inspector-view="lesson"]').click();
  await page.locator('[data-lesson-action="copy"]').click();
  const copy=await page.evaluate(()=>window.__copiedLesson);
  assert(copy.includes(saved.solution.parts[1].steps[0]));
  assert(!copy.includes('对应图形')&&!copy.includes('仅用于图形定位'),'Copy preserves clean mathematical steps');
  await page.locator('[data-lesson-action="read"]').click();
  assert.equal(await page.locator('#readingContent .step-graph-link').count(),0,'Reading/print markup excludes transient graph controls');
  assert(await page.locator('#readingContent .katex').count()>0,'LaTeX remains rendered in expanded reading');
  await page.locator('#readingDialog [data-close-dialog]').click();
  await page.locator('[data-lesson-action="print"]').click();
  assert.equal(await page.locator('#printLesson .step-graph-link').count(),0);
  assert.equal(await page.evaluate(()=>!!window.__printedLesson),true);
  const lastStep=page.locator('#solution [data-step-graph-index]').last();
  await lastStep.click();
  const dependentIds=await page.evaluate(()=>window.DongBoardStep.snapshot());
  const objectIds=JSON.parse(await page.locator('#sceneJson').inputValue()).objects;
  const mId=objectIds.find(o=>o.label==='M').id,nId=objectIds.find(o=>o.label==='N').id;
  assert(dependentIds.ids.includes(mId)&&dependentIds.ids.includes(nId),'The real last step selects resolved derived M/N, not guessed markers');
  await page.locator('[data-inspector-view="geometry"]').click();
  const layerM=page.locator('#layers .layer-row').filter({hasText:/^M(?:\s|·|×|$)/});
  await layerM.locator('input').uncheck();
  assert.equal(await page.evaluate(()=>window.DongBoardStep.snapshot()),null,'Hiding a selected dependent layer clears all transient IDs');
  await page.locator('[data-inspector-view="lesson"]').click();
  assert.equal(await page.locator('.step-graph-toolbar').isHidden(),true,'Hiding a layer also clears the old matched status');
  await page.locator('[data-inspector-view="geometry"]').click();
  await layerM.locator('input').check();
  await page.locator('[data-inspector-view="lesson"]').click();await lastStep.click();
  const movingBefore=await page.evaluate(()=>window.DongBoardLabels.snapshot().placements.find(p=>p.names?.includes('M')));
  await page.locator('[data-inspector-view="geometry"]').click();
  await page.locator('#parameterTarget').selectOption('$dynamic');
  await page.locator('#r-theta').evaluate(input=>{input.value='103';input.dispatchEvent(new Event('input',{bubbles:true}));});
  const movingAfter=await page.evaluate(()=>window.DongBoardLabels.snapshot().placements.find(p=>p.names?.includes('M')));
  assert(movingBefore&&movingAfter&&Number.isFinite(movingAfter.worldX)&&Number.isFinite(movingAfter.worldY));
  assert(Math.abs(movingBefore.worldX-movingAfter.worldX)>1e-5,'Changing a line parameter recomputes the selected dependent point');
  assert.deepEqual(await page.evaluate(()=>window.DongBoardStep.snapshot().ids),dependentIds.ids,'Resolved dynamic highlights keep stable identities while their geometry moves');
  await page.locator('#r-theta').evaluate(input=>{input.value='0';input.dispatchEvent(new Event('input',{bubbles:true}));});
  assert.equal(await page.evaluate(()=>window.DongBoardStep.snapshot()),null,'A degenerate source invalidates dependent selected objects and clears IDs');
  await page.locator('[data-inspector-view="lesson"]').click();
  assert.equal(await page.locator('.step-graph-toolbar').isHidden(),true,'Invalid dependent geometry cannot retain a success status');
  await page.locator('[data-inspector-view="geometry"]').click();await page.locator('#resetParams').click();
  await page.locator('[data-inspector-view="lesson"]').click();await lastStep.click();
  await page.locator('[data-inspector-view="geometry"]').click();
  await page.locator('#layers .layer-row').filter({hasText:/^N(?:\s|·|×|$)/}).locator('.layer-delete').click();
  assert.equal(await page.evaluate(()=>window.DongBoardStep.snapshot()),null,'Deleting a selected dependent point clears IDs');
  await page.locator('[data-inspector-view="lesson"]').click();
  assert.equal(await page.locator('.step-graph-toolbar').isHidden(),true);
  await page.locator('#importLesson').setInputFiles({name:'sourced-beijing-lesson.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(saved))});
  await page.locator('[data-inspector-view="lesson"]').click();await lastStep.click();
  await page.locator('#learningStyle').selectOption('step');
  assert.equal(await page.evaluate(()=>window.DongBoardStep.snapshot()),null,'Hiding the chosen explanation in hint mode clears its board highlight');
  assert.equal(await page.locator('.step-graph-toolbar').isHidden(),true);
  await page.locator('#learningStyle').selectOption('full');
  await page.setViewportSize({width:390,height:844});
  await page.locator('[data-mobile-panel="lesson"]').click();
  const mobileStep=page.locator('#solution [data-step-graph-index]').first();
  await mobileStep.click();
  const bounds=await mobileStep.boundingBox();assert(bounds.height>=40,'Mobile linkage controls retain a touch target');
  const layout=await page.locator('.step-graph-toolbar').evaluate(e=>({left:e.getBoundingClientRect().left,right:e.getBoundingClientRect().right,viewport:innerWidth}));
  assert(layout.left>=0&&layout.right<=layout.viewport,'Linkage status stays within the phone viewport');
  await screenshot('step-graph-link-mobile.png',null);
  const mobileIds=await page.evaluate(()=>window.DongBoardStep.snapshot().ids);
  await page.locator('[data-mobile-panel="board"]').click();
  assert.deepEqual(await page.evaluate(()=>window.DongBoardStep.snapshot().ids),mobileIds,'Switching from explanation to the mobile board preserves the real highlight');
  const orangePixels=await page.locator('#canvas').evaluate(canvas=>{const data=canvas.getContext('2d').getImageData(0,0,canvas.width,canvas.height).data;let count=0;for(let i=0;i<data.length;i+=4)if(data[i]>175&&data[i]<245&&data[i+1]>90&&data[i+1]<180&&data[i+2]<60&&data[i+3]>180)count++;return count;});
  assert(orangePixels>20,'Visible mobile board contains actual orange highlight strokes');
  await screenshot('step-graph-link-mobile-board.png','.board-shell');
  await page.locator('[data-mobile-panel="input"]').click();
  await page.locator('#clearButton').click();
  assert.equal(await page.locator('#solution').isHidden(),true);
  console.log('PASS sourced step-board linkage: keyboard, selected state, literal names, honest misses, no geometry mutation, part/input/restore/reset/hidden/deleted/invalid clearing, live dynamic dependencies, hint mode, clean copy/print and mobile visible highlight');
};
